{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np \n",
    "import plotly.express as px \n",
    "import streamlit as st\n",
    "import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "#### CARREGAR OS DADOS ####\n",
    "Hapvida=pd.read_csv('RECLAMEAQUI_HAPVIDA.csv',sep=',')\n",
    "Ibyte=pd.read_csv('RECLAMEAQUI_IBYTE.csv',sep=',')\n",
    "Nagem=pd.read_csv('RECLAMEAQUI_NAGEM.csv',sep=',')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method NDFrame.head of             ID                                            TEMA  \\\n",
       "0     21898349                Quebraram a tela do meu Notebook   \n",
       "1     22581481           Solicitação de Cancelamento de Compra   \n",
       "2     22579385             Inutilizarão a tela do meu notebook   \n",
       "3     21328791         Produto não faz o que vendedor informa!   \n",
       "4     22608043                       Ibyte não troca o produto   \n",
       "..         ...                                             ...   \n",
       "995  148162149                        Me senti humilhado hoje    \n",
       "996  148246105               Meu notebook retornou arranhado.    \n",
       "997  136408859                     Película com falha no corte   \n",
       "998  146670431  Péssimo atendimento de TI na loja ibyte midway   \n",
       "999  146654995                        Comprei uma memória dd30   \n",
       "\n",
       "                LOCAL       TEMPO  \\\n",
       "0    Hidrolândia - CE  2016-02-11   \n",
       "1          Araxá - MG  2016-03-12   \n",
       "2      Fortaleza - CE  2016-03-12   \n",
       "3      Fortaleza - CE  2016-04-10   \n",
       "4      Fortaleza - CE  2016-05-12   \n",
       "..                ...         ...   \n",
       "995       Recife - PE  2022-09-08   \n",
       "996    Fortaleza - CE  2022-10-08   \n",
       "997    Castanhal - PA  2022-11-01   \n",
       "998      Mossoró - RN  2022-12-07   \n",
       "999    Fortaleza - CE  2022-12-07   \n",
       "\n",
       "                                             CATEGORIA      STATUS  \\\n",
       "0                    Ibyte - Loja Física<->Informática   Resolvido   \n",
       "1    Não consigo fazer operação por telefone<->Cana...  Em réplica   \n",
       "2    Problemas na Loja<->Ibyte - Loja Física<->Prod...  Respondida   \n",
       "3    Ibyte - Loja Física<->Impressoras<->Produto er...  Em réplica   \n",
       "4    Smartphone<->Celulares e Smartphones<->Blackfr...  Respondida   \n",
       "..                                                 ...         ...   \n",
       "995  Acessórios para Celulares, Tablets e Computado...   Resolvido   \n",
       "996  Notebooks<->Mau Atendimento<->Ibyte - Loja Fís...  Respondida   \n",
       "997  Acessórios para Celulares, Tablets e Computado...   Resolvido   \n",
       "998  Computadores all in one<->Mau Atendimento<->Ib...   Resolvido   \n",
       "999  Mau Atendimento<->Máquina fotográfica<->Foto e...  Respondida   \n",
       "\n",
       "                                             DESCRICAO  \\\n",
       "0    Em 05/10/2016 deixei meu Notebook para consert...   \n",
       "1    Prezados, efetuei uma compra no site www.ameri...   \n",
       "2    Decidi conserta meu notebook que parou de inic...   \n",
       "3    Venho através desde canal de reclamação expor ...   \n",
       "4    Comprei um celular na black Friday e com 4 dia...   \n",
       "..                                                 ...   \n",
       "995  Hj me senti Humilhado no Shopping Guararapes P...   \n",
       "996  Em Maio deste ano, meu notebook apresentou um ...   \n",
       "997  Comprei uma película de gel na iByte para o me...   \n",
       "998  na noite de 12/07/2022 comprei um monitor na l...   \n",
       "999  Comprei uma memória na loja ibilyte no shoppin...   \n",
       "\n",
       "                                                   URL   ANO  MES  DIA  \\\n",
       "0    https://www.reclameaqui.com.br//ibyte-loja-fis...  2016    2   11   \n",
       "1    https://www.reclameaqui.com.br//ibyte-loja-fis...  2016    3   12   \n",
       "2    https://www.reclameaqui.com.br//ibyte-loja-fis...  2016    3   12   \n",
       "3    https://www.reclameaqui.com.br//ibyte-loja-fis...  2016    4   10   \n",
       "4    https://www.reclameaqui.com.br//ibyte-loja-fis...  2016    5   12   \n",
       "..                                                 ...   ...  ...  ...   \n",
       "995  https://www.reclameaqui.com.br//ibyte-loja-fis...  2022    9    8   \n",
       "996  https://www.reclameaqui.com.br//ibyte-loja-fis...  2022   10    8   \n",
       "997  https://www.reclameaqui.com.br//ibyte-loja-fis...  2022   11    1   \n",
       "998  https://www.reclameaqui.com.br//ibyte-loja-fis...  2022   12    7   \n",
       "999  https://www.reclameaqui.com.br//ibyte-loja-fis...  2022   12    7   \n",
       "\n",
       "     DIA_DO_ANO  SEMANA_DO_ANO  DIA_DA_SEMANA  TRIMETRES  CASOS  \n",
       "0            42              6              3          1      1  \n",
       "1            72             10              5          1      2  \n",
       "2            72             10              5          1      2  \n",
       "3           101             14              6          2      1  \n",
       "4           133             19              3          2      2  \n",
       "..          ...            ...            ...        ...    ...  \n",
       "995         251             36              3          3      2  \n",
       "996         281             40              5          4      1  \n",
       "997         305             44              1          4      1  \n",
       "998         341             49              2          4      2  \n",
       "999         341             49              2          4      2  \n",
       "\n",
       "[1000 rows x 16 columns]>"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Ibyte.head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "STATUS\n",
       "Resolvido         430\n",
       "Respondida        339\n",
       "Em réplica        124\n",
       "Não resolvido     103\n",
       "Não respondida      4\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##VERICANDO STATUS DO DATAFRAME###\n",
    "Ibyte.STATUS.value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "STATUS\n",
       "Respondida        440\n",
       "Resolvido         238\n",
       "Em réplica        174\n",
       "Não resolvido     147\n",
       "Não respondida      1\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##VERICANDO STATUS DO DATAFRAME###\n",
    "Nagem.STATUS.value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "STATUS\n",
       "Não respondida    639\n",
       "Respondida        271\n",
       "Resolvido          67\n",
       "Em réplica         36\n",
       "Não resolvido       3\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##VERICANDO NÚMERO TOTAL DO STATUS###\n",
    "df_Hapvida.STATUS.value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "## DATETIME ####\n",
    "Hapvida['TEMPO']=pd.to_datetime(Hapvida['TEMPO'])\n",
    "Ibyte['TEMPO']=pd.to_datetime(Ibyte['TEMPO'])\n",
    "Nagem['TEMPO']=pd.to_datetime(Nagem['TEMPO'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [],
   "source": [
    "####CRIAR COLUNA ESTADO EM TODOS OS DATASETS ###\n",
    "Hapvida['LOCAL'].iloc[0].split(' - ')[1].strip()\n",
    "Ibyte['LOCAL'].iloc[0].split(' - ')[1].strip()\n",
    "Nagem['LOCAL'].iloc[0].split(' - ')[1].strip()\n",
    "Hapvida\n",
    "\n",
    "estado_lista=[]\n",
    "for i in range(len(Hapvida)):\n",
    "    estado_lista.append(Hapvida['LOCAL'].iloc[i].split(' - ',2)[1].strip())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'MA',\n",
       " 'GO',\n",
       " 'PA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'AL',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PB',\n",
       " 'SP',\n",
       " 'AL',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PB',\n",
       " 'RN',\n",
       " 'SP',\n",
       " '--',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'MS',\n",
       " 'MS',\n",
       " 'MS',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'AL',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'ES',\n",
       " 'BA',\n",
       " 'MS',\n",
       " 'MA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PB',\n",
       " 'PB',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'AM',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'MT',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'AL',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PA',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'MS',\n",
       " 'RN',\n",
       " 'PA',\n",
       " 'BA',\n",
       " 'AL',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'AL',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PB',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'SE',\n",
       " 'AM',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'MG',\n",
       " 'SE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'AL',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'PA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PA',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'RS',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PA',\n",
       " 'PA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RR',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'PE',\n",
       " 'MS',\n",
       " 'RJ',\n",
       " 'GO',\n",
       " 'RN',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'AM',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PB',\n",
       " 'MG',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'MG',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'PA',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'MT',\n",
       " 'PE',\n",
       " 'MA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'MS',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'MG',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'PA',\n",
       " 'MS',\n",
       " 'PB',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'SE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PA',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PB',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'MA',\n",
       " 'AM',\n",
       " 'PB',\n",
       " 'MS',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'AL',\n",
       " '--',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RJ',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'MA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'MS',\n",
       " 'PB',\n",
       " 'MS',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'AM',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'MS',\n",
       " 'BA',\n",
       " 'RS',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PA',\n",
       " 'SC',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'MS',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'MT',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PB',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'PI',\n",
       " 'CE',\n",
       " 'MS',\n",
       " 'PA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'AM',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SE',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PB',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'ES',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'PI',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SE',\n",
       " 'GO',\n",
       " 'PB',\n",
       " 'CE',\n",
       " 'ES',\n",
       " 'SP',\n",
       " 'AL',\n",
       " 'AL',\n",
       " 'AM',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'MA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'TO',\n",
       " 'SC',\n",
       " 'PE',\n",
       " 'AL',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'MG',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'AM',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'PB',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'AL',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SC',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'SC',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'DF',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'MT',\n",
       " 'BA',\n",
       " 'PB',\n",
       " 'CE',\n",
       " 'MA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SC',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'GO',\n",
       " 'MA',\n",
       " 'PE',\n",
       " 'AM',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'RJ',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'MG',\n",
       " 'PB',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PA',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'MG',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PB',\n",
       " 'SP',\n",
       " 'AM',\n",
       " 'AL',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'MA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'MA',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SC',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'MS',\n",
       " 'RN',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'AL',\n",
       " 'RN',\n",
       " 'PB',\n",
       " 'RN',\n",
       " 'DF',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'PB',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'AM',\n",
       " 'PE',\n",
       " 'MG',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'MS',\n",
       " 'RN',\n",
       " 'DF',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'AL',\n",
       " 'SP',\n",
       " 'PB',\n",
       " 'AM',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'PA',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'AM',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'MA',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PA',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'SE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'PI',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'AL',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PI',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'AM',\n",
       " 'PB',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'MS',\n",
       " 'PE',\n",
       " 'AL',\n",
       " 'MS',\n",
       " 'MS',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'AM',\n",
       " 'MT',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'DF',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'AL',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'MA',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'RN',\n",
       " 'RN',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'PA',\n",
       " 'MS',\n",
       " 'RN',\n",
       " 'SP',\n",
       " 'RN',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PI',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'PB',\n",
       " 'GO',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'BA',\n",
       " 'AM',\n",
       " 'SE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'AL',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'PB',\n",
       " 'SE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'SP',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'GO',\n",
       " 'PE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'AM',\n",
       " 'RS',\n",
       " 'BA',\n",
       " 'DF',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'DF',\n",
       " 'BA',\n",
       " 'AM',\n",
       " 'MT',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'PE',\n",
       " 'RN',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'MA',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'DF',\n",
       " 'PB',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'GO',\n",
       " 'CE',\n",
       " 'PE',\n",
       " 'BA',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'SP',\n",
       " 'SP',\n",
       " 'PB',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'MA',\n",
       " 'GO',\n",
       " 'SP',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'CE',\n",
       " 'RN',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PE',\n",
       " 'PE',\n",
       " 'CE',\n",
       " 'BA',\n",
       " 'SP',\n",
       " 'PB',\n",
       " ...]"
      ]
     },
     "execution_count": 64,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "estado_lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method NDFrame.head of              ID                                             TEMA  \\\n",
       "0     149490335                            TEMPO DE ATENDIMENTO    \n",
       "1     149499817                       Hapvida não tem nutrólogo    \n",
       "2     149498293             Descaso de tratamento de Hemodiálise   \n",
       "3     149495455  DESORGANIZAÇÃO E FALTA DE RESOLUÇÃO DE PROBLEMA   \n",
       "4     149495285                       Liberação de Procedimento    \n",
       "...         ...                                              ...   \n",
       "1011  150005391                                 Mal atendimento    \n",
       "1012  150004057                        Agenda médica nunca abre    \n",
       "1013  150000291                             Péssimo atendimento    \n",
       "1014  150019173                      Imagem dos exames realizado   \n",
       "1015  150001141                            Demora no atendimento   \n",
       "\n",
       "                LOCAL      TEMPO  \\\n",
       "0         Recife - PE 2022-01-09   \n",
       "1       Salvador - BA 2022-01-09   \n",
       "2         Olinda - PE 2022-01-09   \n",
       "3        Goiânia - GO 2022-01-09   \n",
       "4      Fortaleza - CE 2022-01-09   \n",
       "...               ...        ...   \n",
       "1011     Goiânia - GO 2022-12-09   \n",
       "1012   Fortaleza - CE 2022-12-09   \n",
       "1013    Igarassu - PE 2022-12-09   \n",
       "1014       Natal - RN 2022-12-09   \n",
       "1015  Camaragibe - PE 2022-12-09   \n",
       "\n",
       "                                              CATEGORIA          STATUS  \\\n",
       "0     Demora na execução<->Plano<->Planos de Saúde<-...  Não respondida   \n",
       "1     Planos de saúde<->Qualidade do serviço prestad...  Não respondida   \n",
       "2     Demora para autorização de consultas, exames e...      Respondida   \n",
       "3     Demora na execução<->Planos de saúde<->Planos ...  Não respondida   \n",
       "4     Planos de saúde<->Planos de Saúde<->Hapvida Sa...      Respondida   \n",
       "...                                                 ...             ...   \n",
       "1011  Planos de saúde<->Planos de Saúde<->Mau atendi...  Não respondida   \n",
       "1012  Planos de saúde<->Planos de Saúde<->Hapvida Sa...       Resolvido   \n",
       "1013  Mau atendimento do prestador de serviço<->Não ...      Respondida   \n",
       "1014  Exames Lab e imagens<->Não encontrei meu probl...  Não respondida   \n",
       "1015  Exames Lab e imagens<->Horário de atendimento<...  Não respondida   \n",
       "\n",
       "                                              DESCRICAO  \\\n",
       "0     Acabei de sair de uma urgência por causa de at...   \n",
       "1     O Hapvida diz que fornece o serviço de nutrólo...   \n",
       "2     Meu irmão Wagner Santiago, estava internado de...   \n",
       "3     Agendei pelo chat um procedimento onde fui bem...   \n",
       "4     Paguei fatura do plano em atraso e tal atraso ...   \n",
       "...                                                 ...   \n",
       "1011  Fui atendida hoje no dia 09/09/22, na clinica ...   \n",
       "1012  Por vários meses a agenda da Dr. (Editado pelo...   \n",
       "1013  Me encaixaram para um endocrinologista no dia ...   \n",
       "1014  O hapvida tem sido negligente com os pacientes...   \n",
       "1015  Fiz um agendamento de um exame de endoscopia p...   \n",
       "\n",
       "                                                    URL   ANO  MES  DIA  \\\n",
       "0     https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "1     https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "2     https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "3     https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "4     https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "...                                                 ...   ...  ...  ...   \n",
       "1011  https://www.reclameaqui.com.br//hapvida-saude/...  2022   12    9   \n",
       "1012  https://www.reclameaqui.com.br//hapvida-saude/...  2022   12    9   \n",
       "1013  https://www.reclameaqui.com.br//hapvida-saude/...  2022   12    9   \n",
       "1014  https://www.reclameaqui.com.br//hapvida-saude/...  2022   12    9   \n",
       "1015  https://www.reclameaqui.com.br//hapvida-saude/...  2022   12    9   \n",
       "\n",
       "      DIA_DO_ANO  SEMANA_DO_ANO  DIA_DA_SEMANA  TRIMETRES  CASOS  UF ESTADO  \n",
       "0              9              1              6          1     66  PE     PE  \n",
       "1              9              1              6          1     66  BA     BA  \n",
       "2              9              1              6          1     66  PE     PE  \n",
       "3              9              1              6          1     66  GO     GO  \n",
       "4              9              1              6          1     66  CE     CE  \n",
       "...          ...            ...            ...        ...    ...  ..    ...  \n",
       "1011         343             49              4          4     71  GO     GO  \n",
       "1012         343             49              4          4     71  CE     CE  \n",
       "1013         343             49              4          4     71  PE     PE  \n",
       "1014         343             49              4          4     71  RN     RN  \n",
       "1015         343             49              4          4     71  PE     PE  \n",
       "\n",
       "[1016 rows x 18 columns]>"
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Hapvida.head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "lista_locais=Hapvida['ESTADO'].unique()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['PE', 'BA', 'GO', 'CE', 'SP', 'MA', 'PA', 'AL', 'RN', 'PB', '--',\n",
       "       'MS', 'ES', 'AM', 'MT', 'SE', 'MG', 'RS', 'RR', 'RJ', 'SC', 'PI',\n",
       "       'TO', 'DF'], dtype=object)"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "lista_locais"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID</th>\n",
       "      <th>TEMA</th>\n",
       "      <th>LOCAL</th>\n",
       "      <th>TEMPO</th>\n",
       "      <th>CATEGORIA</th>\n",
       "      <th>STATUS</th>\n",
       "      <th>DESCRICAO</th>\n",
       "      <th>URL</th>\n",
       "      <th>ANO</th>\n",
       "      <th>MES</th>\n",
       "      <th>DIA</th>\n",
       "      <th>DIA_DO_ANO</th>\n",
       "      <th>SEMANA_DO_ANO</th>\n",
       "      <th>DIA_DA_SEMANA</th>\n",
       "      <th>TRIMETRES</th>\n",
       "      <th>CASOS</th>\n",
       "      <th>UF</th>\n",
       "      <th>ESTADO</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>149490335</td>\n",
       "      <td>TEMPO DE ATENDIMENTO</td>\n",
       "      <td>Recife - PE</td>\n",
       "      <td>2022-01-09</td>\n",
       "      <td>Demora na execução&lt;-&gt;Plano&lt;-&gt;Planos de Saúde&lt;-...</td>\n",
       "      <td>Não respondida</td>\n",
       "      <td>Acabei de sair de uma urgência por causa de at...</td>\n",
       "      <td>https://www.reclameaqui.com.br//hapvida-saude/...</td>\n",
       "      <td>2022</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>66</td>\n",
       "      <td>PE</td>\n",
       "      <td>PE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>149499817</td>\n",
       "      <td>Hapvida não tem nutrólogo</td>\n",
       "      <td>Salvador - BA</td>\n",
       "      <td>2022-01-09</td>\n",
       "      <td>Planos de saúde&lt;-&gt;Qualidade do serviço prestad...</td>\n",
       "      <td>Não respondida</td>\n",
       "      <td>O Hapvida diz que fornece o serviço de nutrólo...</td>\n",
       "      <td>https://www.reclameaqui.com.br//hapvida-saude/...</td>\n",
       "      <td>2022</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>66</td>\n",
       "      <td>BA</td>\n",
       "      <td>BA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>149498293</td>\n",
       "      <td>Descaso de tratamento de Hemodiálise</td>\n",
       "      <td>Olinda - PE</td>\n",
       "      <td>2022-01-09</td>\n",
       "      <td>Demora para autorização de consultas, exames e...</td>\n",
       "      <td>Respondida</td>\n",
       "      <td>Meu irmão Wagner Santiago, estava internado de...</td>\n",
       "      <td>https://www.reclameaqui.com.br//hapvida-saude/...</td>\n",
       "      <td>2022</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>66</td>\n",
       "      <td>PE</td>\n",
       "      <td>PE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>149495455</td>\n",
       "      <td>DESORGANIZAÇÃO E FALTA DE RESOLUÇÃO DE PROBLEMA</td>\n",
       "      <td>Goiânia - GO</td>\n",
       "      <td>2022-01-09</td>\n",
       "      <td>Demora na execução&lt;-&gt;Planos de saúde&lt;-&gt;Planos ...</td>\n",
       "      <td>Não respondida</td>\n",
       "      <td>Agendei pelo chat um procedimento onde fui bem...</td>\n",
       "      <td>https://www.reclameaqui.com.br//hapvida-saude/...</td>\n",
       "      <td>2022</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>66</td>\n",
       "      <td>GO</td>\n",
       "      <td>GO</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>149495285</td>\n",
       "      <td>Liberação de Procedimento</td>\n",
       "      <td>Fortaleza - CE</td>\n",
       "      <td>2022-01-09</td>\n",
       "      <td>Planos de saúde&lt;-&gt;Planos de Saúde&lt;-&gt;Hapvida Sa...</td>\n",
       "      <td>Respondida</td>\n",
       "      <td>Paguei fatura do plano em atraso e tal atraso ...</td>\n",
       "      <td>https://www.reclameaqui.com.br//hapvida-saude/...</td>\n",
       "      <td>2022</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>66</td>\n",
       "      <td>CE</td>\n",
       "      <td>CE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>136389337</td>\n",
       "      <td>Devolução de ingresso e estorno de pagemento</td>\n",
       "      <td>Recife - PE</td>\n",
       "      <td>2022-11-01</td>\n",
       "      <td>Outro Tipo de produto/Serviço&lt;-&gt;Nagem - Loja F...</td>\n",
       "      <td>Não resolvido</td>\n",
       "      <td>Fiz a compra de 4 ingressos para o evento olin...</td>\n",
       "      <td>https://www.reclameaqui.com.br//nagem-loja-fis...</td>\n",
       "      <td>2022</td>\n",
       "      <td>11</td>\n",
       "      <td>1</td>\n",
       "      <td>305</td>\n",
       "      <td>44</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>PE</td>\n",
       "      <td>PE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>148342817</td>\n",
       "      <td>PRODUTO  NA LOJA SEM SOLUÇAO</td>\n",
       "      <td>Aracaju - SE</td>\n",
       "      <td>2022-11-08</td>\n",
       "      <td>Nagem - Loja Física&lt;-&gt;Produto com defeito&lt;-&gt;Nã...</td>\n",
       "      <td>Respondida</td>\n",
       "      <td>COMPREI UM NOTEBOOK E UM MONITOR NA LOJA DO SH...</td>\n",
       "      <td>https://www.reclameaqui.com.br//nagem-loja-fis...</td>\n",
       "      <td>2022</td>\n",
       "      <td>11</td>\n",
       "      <td>8</td>\n",
       "      <td>312</td>\n",
       "      <td>45</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>SE</td>\n",
       "      <td>SE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>138318051</td>\n",
       "      <td>Mercadoria com avaria e troca recusada</td>\n",
       "      <td>Salvador - BA</td>\n",
       "      <td>2022-12-02</td>\n",
       "      <td>Nagem - Loja Física&lt;-&gt;Geladeira-Refrigerador&lt;-...</td>\n",
       "      <td>Respondida</td>\n",
       "      <td>No dia 28/01 para minha infelicidade fui na Lo...</td>\n",
       "      <td>https://www.reclameaqui.com.br//nagem-loja-fis...</td>\n",
       "      <td>2022</td>\n",
       "      <td>12</td>\n",
       "      <td>2</td>\n",
       "      <td>336</td>\n",
       "      <td>48</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>BA</td>\n",
       "      <td>BA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>146640397</td>\n",
       "      <td>Compra insatisfatória - NAGEM SHOPPING DA ILHA...</td>\n",
       "      <td>São Luís - MA</td>\n",
       "      <td>2022-12-07</td>\n",
       "      <td>Nagem - Loja Física&lt;-&gt;Produto com defeito&lt;-&gt;In...</td>\n",
       "      <td>Resolvido</td>\n",
       "      <td>Boa tarde!No dia 01 de Julho de 2022, fiz uma ...</td>\n",
       "      <td>https://www.reclameaqui.com.br//nagem-loja-fis...</td>\n",
       "      <td>2022</td>\n",
       "      <td>12</td>\n",
       "      <td>7</td>\n",
       "      <td>341</td>\n",
       "      <td>49</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>MA</td>\n",
       "      <td>MA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>148413453</td>\n",
       "      <td>Produto Queimado e não foi realizado troca</td>\n",
       "      <td>Caruaru - PE</td>\n",
       "      <td>2022-12-08</td>\n",
       "      <td>Produto com defeito&lt;-&gt;Nagem - Loja Física&lt;-&gt;Im...</td>\n",
       "      <td>Em réplica</td>\n",
       "      <td>Fiz uma compra de uma impressora Nota fiscal n...</td>\n",
       "      <td>https://www.reclameaqui.com.br//nagem-loja-fis...</td>\n",
       "      <td>2022</td>\n",
       "      <td>12</td>\n",
       "      <td>8</td>\n",
       "      <td>342</td>\n",
       "      <td>49</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>PE</td>\n",
       "      <td>PE</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>3016 rows × 18 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            ID                                               TEMA  \\\n",
       "0    149490335                              TEMPO DE ATENDIMENTO    \n",
       "1    149499817                         Hapvida não tem nutrólogo    \n",
       "2    149498293               Descaso de tratamento de Hemodiálise   \n",
       "3    149495455    DESORGANIZAÇÃO E FALTA DE RESOLUÇÃO DE PROBLEMA   \n",
       "4    149495285                         Liberação de Procedimento    \n",
       "..         ...                                                ...   \n",
       "995  136389337       Devolução de ingresso e estorno de pagemento   \n",
       "996  148342817                      PRODUTO  NA LOJA SEM SOLUÇAO    \n",
       "997  138318051             Mercadoria com avaria e troca recusada   \n",
       "998  146640397  Compra insatisfatória - NAGEM SHOPPING DA ILHA...   \n",
       "999  148413453         Produto Queimado e não foi realizado troca   \n",
       "\n",
       "              LOCAL      TEMPO  \\\n",
       "0       Recife - PE 2022-01-09   \n",
       "1     Salvador - BA 2022-01-09   \n",
       "2       Olinda - PE 2022-01-09   \n",
       "3      Goiânia - GO 2022-01-09   \n",
       "4    Fortaleza - CE 2022-01-09   \n",
       "..              ...        ...   \n",
       "995     Recife - PE 2022-11-01   \n",
       "996    Aracaju - SE 2022-11-08   \n",
       "997   Salvador - BA 2022-12-02   \n",
       "998   São Luís - MA 2022-12-07   \n",
       "999    Caruaru - PE 2022-12-08   \n",
       "\n",
       "                                             CATEGORIA          STATUS  \\\n",
       "0    Demora na execução<->Plano<->Planos de Saúde<-...  Não respondida   \n",
       "1    Planos de saúde<->Qualidade do serviço prestad...  Não respondida   \n",
       "2    Demora para autorização de consultas, exames e...      Respondida   \n",
       "3    Demora na execução<->Planos de saúde<->Planos ...  Não respondida   \n",
       "4    Planos de saúde<->Planos de Saúde<->Hapvida Sa...      Respondida   \n",
       "..                                                 ...             ...   \n",
       "995  Outro Tipo de produto/Serviço<->Nagem - Loja F...   Não resolvido   \n",
       "996  Nagem - Loja Física<->Produto com defeito<->Nã...      Respondida   \n",
       "997  Nagem - Loja Física<->Geladeira-Refrigerador<-...      Respondida   \n",
       "998  Nagem - Loja Física<->Produto com defeito<->In...       Resolvido   \n",
       "999  Produto com defeito<->Nagem - Loja Física<->Im...      Em réplica   \n",
       "\n",
       "                                             DESCRICAO  \\\n",
       "0    Acabei de sair de uma urgência por causa de at...   \n",
       "1    O Hapvida diz que fornece o serviço de nutrólo...   \n",
       "2    Meu irmão Wagner Santiago, estava internado de...   \n",
       "3    Agendei pelo chat um procedimento onde fui bem...   \n",
       "4    Paguei fatura do plano em atraso e tal atraso ...   \n",
       "..                                                 ...   \n",
       "995  Fiz a compra de 4 ingressos para o evento olin...   \n",
       "996  COMPREI UM NOTEBOOK E UM MONITOR NA LOJA DO SH...   \n",
       "997  No dia 28/01 para minha infelicidade fui na Lo...   \n",
       "998  Boa tarde!No dia 01 de Julho de 2022, fiz uma ...   \n",
       "999  Fiz uma compra de uma impressora Nota fiscal n...   \n",
       "\n",
       "                                                   URL   ANO  MES  DIA  \\\n",
       "0    https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "1    https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "2    https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "3    https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "4    https://www.reclameaqui.com.br//hapvida-saude/...  2022    1    9   \n",
       "..                                                 ...   ...  ...  ...   \n",
       "995  https://www.reclameaqui.com.br//nagem-loja-fis...  2022   11    1   \n",
       "996  https://www.reclameaqui.com.br//nagem-loja-fis...  2022   11    8   \n",
       "997  https://www.reclameaqui.com.br//nagem-loja-fis...  2022   12    2   \n",
       "998  https://www.reclameaqui.com.br//nagem-loja-fis...  2022   12    7   \n",
       "999  https://www.reclameaqui.com.br//nagem-loja-fis...  2022   12    8   \n",
       "\n",
       "     DIA_DO_ANO  SEMANA_DO_ANO  DIA_DA_SEMANA  TRIMETRES  CASOS  UF ESTADO  \n",
       "0             9              1              6          1     66  PE     PE  \n",
       "1             9              1              6          1     66  BA     BA  \n",
       "2             9              1              6          1     66  PE     PE  \n",
       "3             9              1              6          1     66  GO     GO  \n",
       "4             9              1              6          1     66  CE     CE  \n",
       "..          ...            ...            ...        ...    ...  ..    ...  \n",
       "995         305             44              1          4      1  PE     PE  \n",
       "996         312             45              1          4      1  SE     SE  \n",
       "997         336             48              4          4      1  BA     BA  \n",
       "998         341             49              2          4      1  MA     MA  \n",
       "999         342             49              3          4      1  PE     PE  \n",
       "\n",
       "[3016 rows x 18 columns]"
      ]
     },
     "execution_count": 69,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "##UNIFICANDO DATAFRAMES ## \n",
    "GERAL = pd.concat ( [Hapvida, Ibyte, Nagem])\n",
    "GERAL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#### STREAMLIT###\n",
    "st.title('DASHBOARD - RECLAME AQUI - IBYTE, HAPVIDA E NAGEM')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "st.write('Esse dashboard apresenta dados do Reclame Aqui da Ibyte, HapVida e Nagem')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [],
   "source": [
    "lista_locais=GERAL['ESTADO'].unique()\n",
    "local = st.selectbox(\n",
    "    'Selecione o local',\n",
    "    lista_locais)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
